environment:
  name: A
  version:

server:
  port: 8001

logging:
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: warn
    cn:
      caohongliang:
        gray:
          core: debug
debug: true