
server:
  port: 8000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true

logging:
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: warn
    cn:
      caohongliang:
        gray:
          core: info
debug: true