environment:
  name: A
  version:

server:
  port: 8003

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: warn
    cn:
      caohongliang:
        gray:
          core: debug
debug: true